title:              ""
email:              me@wesleydickens.com
author:             Wesley Dickens
url:                "https://wesleydickens.com"

# Social Profiles
social_username: wesleydickens

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate